version: '3.8' 
  
services:
  django:
    build:
      context: .
    volumes:
      - "./movies_admin:/movies_admin"
    env_file:
      - "movies_admin/config/.env"
    depends_on:
      - database
      - elasticsearch
  
  database:

    image: postgres:15.7

    environment:
    
      - POSTGRES_DB=movies_database
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
    
    volumes:
      - /opt/homebrew/var/postgresql@15:/var/lib/postgresql/data 
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./movies_admin/movies_admin/staticfiles/admin:/etc/nginx/movies_admin/movies_admin/staticfiles/admin"
      - "./movies_admin/movies_admin/staticfiles/rest_framework:/etc/nginx/movies_admin/movies_admin/staticfiles/rest_framework"
    ports:
      - "80:80"
    depends_on:
      - django
  
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  
  redis:
    image: redis:7.2.4

